backend/controllers/CreateOrderController.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 13.06.2018
 * Time: 23:42
 */

namespace backend\controllers;


use backend\models\Paper;
use backend\models\TypeOrder;
use backend\models\TypePrint;
use Yii;
use yii\web\Controller;
use backend\models\Customer;
use backend\models\Order;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;

class CreateOrderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['customer', 'order', 'order-success', 'canceled-order', 'suspend-order'],
                'rules' => [
                    [
                        'actions' => ['customer','order','order-success', 'canceled-order', 'suspend-order'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionCustomer()
    {
        $model = new Customer();

        $secondName = Yii::$app->request->post('second_name');
        $firstName = Yii::$app->request->post('first_name');
        $patronymic = Yii::$app->request->post('patronymic');
        $email = Yii::$app->request->post('email');
        $phone = Yii::$app->request->post('phone');
        $secondPhone = Yii::$app->request->post('second_phone');

        if ($firstName != null && $secondName != null && $patronymic != null
        && $email != null && $phone != null)
        {
            $model->full_name = $secondName.' '.$firstName.' '.$patronymic;
            $model->email = $email;
            $model->phone = $phone;
            $model->second_phone = $secondPhone;
            $model->created_at = date(' d/m/Y H:i:s');
            if ($model->save())
            {
                return $this->redirect(['order', 'id' => $model->id]);
            }
        }

        return $this->render('customer',[
            'model' => $model
        ]);
    }

    public function actionOrder($id)
    {
        $model = new Order();

        $model->customer_id = Yii::$app->request->post('customer_id');
        $model->created_at = date('d/m/Y H:i:s');
        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect(['order-success', 'id' => $model->id]);
        }

        return $this->render('order',[
            'model' => $model,
            'id' => $id
        ]);
    }

    public function actionCloneOrder()
    {
        $model = new Order();

        $model->customer_id = Yii::$app->request->post('customer_id');
        $model->created_at = date('d/m/Y H:i:s');

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect(['order-success', 'id' => $model->id]);
        }

        $errorMsg = 'Клонирование не возможно';
        return $errorMsg;
    }

    public function actionEditOrder()
    {
        $id = Yii::$app->request->post('id');

        $model = Order::findOne(['id' => $id]);

        $model->customer_id = Yii::$app->request->post('customer_id');
        $model->updated_at = date('d/m/Y H:i:s');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['order-success', 'id' => $model->id]);
        }

        $errorMsg = 'Редактирование не возможно';
        return $errorMsg;
    }

    public function actionOrderSuccess($id)
    {
        $model = Order::findOne(['id' => $id]);

        return $this->render('order-success',[
            'model' => $model
        ]);
    }

    public function actionGetPrice()
    {
        $type = Yii::$app->request->post('type');
        $paper = Yii::$app->request->post('paper');
        $typePrint = Yii::$app->request->post('typePrint');
        $edition = Yii::$app->request->post('edition');
        $sides = Yii::$app->request->post('sides');
        $service = Yii::$app->request->post('service');

        $type = TypeOrder::findOne(['id' => $type])->price;
        $paper = Paper::findOne(['id' => $paper])->price;
        $typePrint = TypePrint::findOne(['id' => $typePrint])->price;

        $price = (($paper + $typePrint) * ($edition * $sides)) + $type;

        return json_encode($price);
    }

    public function actionGetModal()
    {
        $orderID = Yii::$app->request->post('order');
        $modalType = Yii::$app->request->post('type');
        $model = Order::findOne(['id' => $orderID]);

        return $this->renderAjax('_modal', [
            'model' => $model,
            'modal' => $modalType
        ]);
    }

    public function actionCustomerHistory()
    {
        $customer = Yii::$app->request->post('customer');

        $customer = Customer::findOne(['phone' => $customer]);
        if ($customer != null)
        {
            $query = Order::find();

            $dataProvider = new ActiveDataProvider([
                'query' => $query->where(['customer_id' => $customer->id]),
                'sort' => ['defaultOrder'=>['id' => SORT_DESC]],
                'pagination' => false
            ]);

            return $this->renderAjax('customer_history',[
                'dataProvider' => $dataProvider,
                'customer' => $customer
            ]);
        }
        $errorMsg = 'Такого клиента не существует';
        return $errorMsg;
    }

    public function actionPayModal()
    {
        $orderID = Yii::$app->request->post('order');

        $model = Order::findOne(['id' => $orderID]);

        return $this->renderAjax('_modal_pay', [
            'model' => $model
        ]);
    }

    public function actionSetPaid()
    {
        $amount = Yii::$app->request->post('amount');
        $orderID = Yii::$app->request->post('order');

        $model = Order::findOne(['id' => $orderID]);

        $model->paid_out += $amount;

        $model->save();

        return $this->renderAjax('_modal_pay', [
            'model' => $model
        ]);
    }

    public function actionCloseOrder()
    {
        $orderID = Yii::$app->request->post('order');

        $model = Order::findOne(['id' => $orderID]);

        $model->state = 1;
        $model->completed = date('d/m/Y H:i:s');
        $model->save();

        return $this->redirect(['order-success', 'id' => $model->id]);
    }

    public function actionControlModal()
    {
        $orderID = Yii::$app->request->post('order');

        $model = Order::findOne(['id' => $orderID]);

        return $this->renderAjax('_modal_control', [
            'model' => $model
        ]);
    }

    public function actionSuspendOrder()
    {
        $orderID = Yii::$app->request->post('order');

        $model = Order::findOne(['id' => $orderID]);

        if ($model->state == 2)
        {
            $model->state = 0;
        } else {
            $model->state = 2;
        }

        $model->save();

        return $this->redirect(['order-success', 'id' => $model->id]);
    }

    public function actionPrintOrder()
    {
        $id = Yii::$app->request->get('id');

        $model = Order::findOne(['id'=>$id]);

        $content = $this->renderPartial('_data_print', [
            'model' => $model,
        ]);
        $pdf = new \kartik\mpdf\Pdf([
            'mode' => \kartik\mpdf\Pdf::MODE_UTF8,
            'content' => $content,
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'cssInline' => '.kv-heading-1{font-size:18px}',
            'options' => [
                'title' => 'Заказ на имя '.$model->customer->full_name,
                'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
            ],
            'methods' => [
                'SetHeader' => ['flyer.loc||Generated On: ' . date("r")],
//                'SetFooter' => ['|Page {PAGENO}|'],
            ]
        ]);
        return $pdf->render();
    }

    public function actionCanceledOrder()
    {
        $orderID = Yii::$app->request->post('order');

        $model = Order::findOne(['id' => $orderID]);

        $model->state = 3;
        $model->completed = date('d/m/Y H:i:s');
        $model->save();

        return $this->redirect(['order-success', 'id' => $model->id]);
    }

    public function actionFirstName()
    {
        $qq = Yii::$app->request->get('term');
        $query = Customer::find()->select(['full_name as value'])->where(['like','full_name', $qq])
            ->asArray('title')
            ->all();
        $result = array();
        foreach($query as $q){
            if (strstr($q['value'], $qq)) {
                $result[] = array('value' => explode(' ', $q['value'])[1]);
            }
        }
        return json_encode($result);
    }

    public function actionSecondName()
    {
        $qq = Yii::$app->request->get('term');
        $query = Customer::find()->select(['full_name as value'])->where(['like','full_name', $qq])
            ->asArray('title')
            ->all();
        $result = array();
        foreach($query as $q){
            if (strstr($q['value'], $qq)) {
                $result[] = array('value' => explode(' ', $q['value'])[0]);
            }
        }
        return json_encode($result);
    }

    public function actionPatronymic()
    {
        $qq = Yii::$app->request->get('term');
        $query = Customer::find()->select(['full_name as value'])->where(['like','full_name', $qq])
            ->asArray('title')
            ->all();
        $result = array();
        foreach($query as $q){
            if (strstr($q['value'], $qq)) {
                $result[] = array('value' => explode(' ', $q['value'])[2]);
            }
        }
        return json_encode($result);
    }

    public function actionPhone()
    {
        $qq = Yii::$app->request->get('term');
        $query = Customer::find()->select(['phone as value'])->where(['like','phone', $qq])
            ->asArray('title')

backend/views/create-order/_data_history.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 15.06.2018
 * Time: 15:55
 */

use yii\bootstrap\Modal;
use yii\helpers\Html;

/* @var $this \yii\web\view */
/* @var $model \backend\models\Order */
/* @var $form  \yii\widgets\ActiveForm */

?>
<div class="order-data-history">
    <div class="order-history-info">
        <table>
            <tr>
                <td><b>Номер заказа:</b></td>
                <td><?= $model->id ?></td>
            </tr>
            <tr>
                <td><b>Статус заказа:</b></td>
                <td>
                    <?php if ($model->status == 0): ?>
                        Простой заказ
                    <?php elseif ($model->status == 1): ?>
                        Важный заказ
                    <?php elseif ($model->status == 2): ?>
                        Срочный заказ
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td><b>Свойства заказа:</b></td>
                <td>
                    <span class="badge"><?= $model->typeOrder->type ?></span>
                    <span class="badge"><?= $model->typePaper->type ?></span>
                    <span class="badge"><?= $model->typePrint->type ?></span>
                    <?php if ($model->sides == 1): ?>
                        <span class="badge">односторонняя печать</span>
                    <?php else: ?>
                        <span class="badge">двухсторонняя печать</span>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td><b>Дополнительные услуги:</b></td>
                <td>
                    <?php if ($model->service == 0): ?>
                        без дизайна
                    <?php else: ?>
                        с дизайном
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td><b>Тираж:</b></td>
                <td><?= $model->edition ?></td>
            </tr>
            <tr>
                <td><b>Цена:</b></td>
                <td><?= $model->price ?></td>
            </tr>
            <tr>
                <td><b>Выплачено</b></td>
                <td><?= $model->paid_out ?></td>
            </tr>
            <tr>
                <td><b>Создан</b></td>
                <td><?= $model->created_at ?></td>
            </tr>
            <?php if ($model->state == 2): ?>
                <p><span class="badge badge-order-warning">Приостановлен: <b>Deadline:</b> <?= $model->deadline ?></span></p>
            <?php else: ?>
                <tr>
                    <td><b>Deadline:</b></td>
                    <td><?= $model->deadline ?></td>
                </tr>
                <?php if ($model->state == 3): ?>
                    <p><span class="badge badge-order-canceled"><b>Отменен:</b> <?= $model->completed ?></span></p>
                <?php else: ?>
                    <?php if ($model->completed != null): ?>
                        <p><span class="badge badge-order-success"><b>Выполнен:</b> <?= $model->completed ?></span></p>
                    <?php else: ?>
                        <p><span class="badge badge-order-wait"><b>Выполняется</b></span></p>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </table>
    </div>
    <div class="order-history-control">
        <?= Html::a('<span class="glyphicon glyphicon-eye-open"></span>',['/create-order/order-success', 'id' => $model->id], ['class' => 'btn btn-control', 'data-pjax' => false]) ?>
        <?php if ($model->completed == null): ?>
            <?php
            Modal::begin([
                'toggleButton' => [
                    'label' => '<span class="glyphicon glyphicon-cog"></span>',
                    'tag' => 'button',
                    'data-id' => $model->id,
                    'class' => 'btn btn-control edit-order-btn',
                    'id' => 'btn-edit-order'
                ],
                'id' => 'edit-order',//.$model->id,
                'header' => '<h2>Редактирование заказа</h2>'

            ]);
            ?>
            <div class="wrapper" id="#loading">
                <div class="inner">
                    <span>З</span>
                    <span>а</span>
                    <span>г</span>
                    <span>р</span>
                    <span>у</span>
                    <span>з</span>
                    <span>к</span>
                    <span>а</span>
                </div>
            </div>
            <?php Modal::end(); ?>
        <?php endif; ?>
        <?php
        Modal::begin([
            'toggleButton' => [
                'label' => '<span class="glyphicon glyphicon-copy"></span>',
                'tag' => 'button',
                'data-id' => $model->id,
                'class' => 'btn btn-control copy-order-btn',
                'id' => 'btn-copy-order'
            ],
            'id' => 'copy-order',//.$model->id,
            'header' => '<h2>Клонирование заказа</h2>'

        ]);
        ?>
        <div id="loading">
            <div class="wrapper">
                <div class="inner">
                    <span>З</span>
                    <span>а</span>
                    <span>г</span>
                    <span>р</span>
                    <span>у</span>
                    <span>з</span>
                    <span>к</span>
                    <span>а</span>
                </div>
            </div>
        </div>
        <?php Modal::end(); ?>
        <?= Html::a('<span class="glyphicon glyphicon-print"></span>',['/create-order/print-order', 'id' => $model->id], ['class' => 'btn btn-control btn-print']) ?>
        <?php if ($model->completed == null): ?>
            <?php
            Modal::begin([
                'toggleButton' => [
                    'label' => '<span class="glyphicon glyphicon-off"></span>',
                    'tag' => 'button',
                    'data-id' => $model->id,
                    'class' => 'btn btn-control off-order-btn',
                    'id' => 'off-order-btn'
                ],
                'id' => 'off-order',//.$model->id,
                'header' => '<h3>Управление</h3>'

            ]);
            ?>
            <div id="loading">
                <div class="wrapper">
                    <div class="inner">
                        <span>З</span>
                        <span>а</span>
                        <span>г</span>
                        <span>р</span>
                        <span>у</span>
                        <span>з</span>
                        <span>к</span>
                        <span>а</span>
                    </div>
                </div>
            </div>
            <?php Modal::end(); ?>
        <?php endif; ?>
        <?php if ($model->completed == null): ?>
            <?php
            Modal::begin([
                'toggleButton' => [
                    'label' => '<span class="glyphicon glyphicon-ok"></span>',
                    'tag' => 'button',
                    'data-id' => $model->id,
                    'class' => 'btn btn-control btn-order-completed',
                    'id' => 'btn-order-completed'
                ],
                'id' => 'completed-order',//.$model->id,
                'header' => '<h2>Выполнение заказа</h2>'

            ]);
            ?>
            <div id="loading">
                <div class="wrapper">
                    <div class="inner">
                        <span>З</span>
                        <span>а</span>
                        <span>г</span>
                        <span>р</span>
                        <span>у</span>
                        <span>з</span>
                        <span>к</span>
                        <span>а</span>
                    </div>
                </div>
            </div>
            <?php Modal::end(); ?>
        <?php endif; ?>
    </div>
</div>

backend/views/create-order/_data_print.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 01.09.2018
 * Time: 13:04
 */

/* @var $this \yii\web\View */
/* @var $model \backend\models\Order */

?>

<p><?= $model->id ?></p>
<p><?= $model->customer->full_name ?></p>
<p><?= $model->customer->phone ?></p>

backend/views/create-order/_modal.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 06.07.2018
 * Time: 13:38
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use backend\models\Paper;
use backend\models\TypePrint;
use backend\models\TypeOrder;
use kartik\datetime\DateTimePicker;

/* @var $this \yii\web\view */
/* @var $model \backend\models\Order */
/* @var $form \yii\widgets\ActiveForm */
/* @var $modal string */

?>
<div class="display-modal" id="display-modal">
    <?php $form = ActiveForm::begin([
        'action' => ['/create-order/'.$modal.'-order']
    ]); ?>

    <?= Html::hiddenInput('id', $model->id) ?>
    <?= Html::hiddenInput('customer_id', $model->customer_id) ?>

    <?= $form->field($model, 'type')->dropDownList(ArrayHelper::map(TypeOrder::find()->all(), 'id', 'type'),[
        'prompt' => 'Тип заказа',
        'class' => 'form-control order-type'
    ])->label(false) ?>

    <?= $form->field($model, 'service')->radioList([
        '0' => 'без дизайна',
        '1' => 'с дизайном',
    ], ['class' => 'order-service'])->label(false) ?>

    <?= $form->field($model, 'paper')->dropDownList(ArrayHelper::map(Paper::find()->all(), 'id', 'type'),[
        'prompt' => 'Бумага',
        'class' => 'form-control order-paper'
    ])->label(false) ?>

    <?= $form->field($model, 'type_print')->dropDownList(ArrayHelper::map(TypePrint::find()->all(), 'id', 'type'),[
        'prompt' => 'Тип печати',
        'class' => 'form-control order-type-print'
    ])->label(false) ?>

    <?= $form->field($model, 'sides')->dropDownList([
        '1' => 'односторонняя печать',
        '2' => 'двухсторонняя печать',
    ],['class' => 'form-control order-sides'])->label(false) ?>

    <?= $form->field($model, 'edition')->textInput(['class' => 'form-control order-edition']) ?>

    <div class="price-order-block">
        <div class="price-order-input">
            <?= $form->field($model, 'price')->textInput(['maxlength' => true, 'class' => 'form-control order-price']) ?>
        </div>
        <div class="price-order-input-btn">
            <button type="button" class="price-order-btn btn btn-success" data-id="<?= $model->id ?>"><span class="glyphicon glyphicon-retweet"></span></button>
        </div>
    </div>

    <?= $form->field($model, 'description')->textarea(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textarea(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->dropDownList([
        '0' => 'Простой заказ',
        '1' => 'Важный заказ',
        '2' => 'Срочный заказ',
    ]) ?>

    <?= $form->field($model, 'deadline')->widget(DateTimePicker::classname(), [
        'options' => ['placeholder' => 'Enter event time ...','class' => 'form-control modal-sm',],
        'name' => 'dp_4'.$model->id,
        'id' => $model->id,
        'language' => 'ru-RU',
        'type' => DateTimePicker::TYPE_INLINE,
        'pluginOptions' => [
            'format' => 'D, dd-M-yyyy, hh:ii',
        ]
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary clone-btn']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

backend/views/create-order/_modal_control.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 07.07.2018
 * Time: 17:06
 */

use yii\helpers\Html;

/* @var $this \yii\web\view */
/* @var $model \backend\models\Order */

?>
<?php if ($model->state == 2): ?>
    <div class="form-group">
        <?= Html::button('<span class="glyphicon glyphicon-play"></span> Восстановить заказ', ['class' => 'btn btn-save pause-order-btn form-control', 'data-id' => $model->id]); ?>
    </div>
<?php elseif ($model->state != 3): ?>
    <div class="form-group">
        <?= Html::button('<span class="glyphicon glyphicon-pause"></span> Приостановить заказ', ['class' => 'btn btn-pause pause-order-btn form-control', 'data-id' => $model->id]); ?>
    </div>
<?php endif; ?>
<div class="form-group">
    <?= Html::button('<span class="glyphicon glyphicon-remove"></span> Отменить заказ', ['class' => 'btn btn-canceled canceled-order-btn form-control', 'data-id' => $model->id]); ?>
</div>

backend/views/create-order/_modal_pay.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 07.07.2018
 * Time: 15:25
 */

use yii\helpers\Html;

/* @var $this \yii\web\view */
/* @var $model \backend\models\Order */

?>
<div class="display-modal">
    <?php if ($model->price != $model->paid_out): ?>
        <p><b>Необходимая сумма для выполнения:</b> <?= $model->price - $model->paid_out ?></p>
        <p>Введите сумму которую внес клиент:</p>
        <div class="form-group">
            <?= Html::input('text','paid_out'.$model->id,'',['class' => 'form-control order-amount']); ?>
        </div>
        <div class="form-group">
            <?= Html::button('Внести деньги', ['class' => 'btn btn-save form-control btn-set-paid', 'data-id' => $model->id]); ?>
        </div>
    <?php elseif ($model->price == $model->paid_out): ?>
        <?= Html::button('Закрыть заказ',['class' => 'btn btn-save form-control btn-close-order', 'data-id' => $model->id]); ?>
    <?php endif;?>
</div>

backend/views/create-order/customer.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 13.06.2018
 * Time: 23:46
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\AutoComplete;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model backend\models\Customer */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Create customer';
$this->registerJsFile(Yii::getAlias('@web') . '/js/customer.js', ['depends' => [yii\web\JqueryAsset::className()]]);
?>

<div class="customer-form">
    <h2 class="title-customer">Оформление клиента</h2>
    <div class="customer-block">
        <?php $form = ActiveForm::begin(); ?>

        <div class="full-name-block">
            <div class="customer-elem">
                <span class="customer-label">Фамилия</span>
                <?= AutoComplete::widget([
                    'name' => 'second_name',
                    'options' => ['class' => 'form-control'],
                    'clientOptions' => [
                        'source' => Url::to(['create-order/second-name']),
                        'minLength'=>'1',
                        'limit' => '1'
                    ],
                ]); ?>
            </div>
            <div class="customer-elem">
                <span class="customer-label">Имя</span>
                <?= AutoComplete::widget([
                    'name' => 'first_name',
                    'options' => ['class' => 'form-control'],
                    'clientOptions' => [
                        'source' => Url::to(['create-order/first-name']),
                        'minLength'=>'1',
                        'limit' => '1'
                    ],
                ]); ?>
            </div>
            <div class="customer-elem">
                <span class="customer-label">Отчество</span>
                <?= AutoComplete::widget([
                    'name' => 'patronymic',
                    'options' => ['class' => 'form-control'],
                    'clientOptions' => [
                        'source' => Url::to(['create-order/patronymic']),
                        'minLength'=>'1',
                        'limit' => '1'
                    ],
                ]); ?>
            </div>
        </div>

        <div class="customer-info">
            <span class="customer-label">Email</span>
            <?= Html::textInput('email', '',['class' => 'form-control']) ?>
            <span class="customer-label">Телефон</span>
            <?= AutoComplete::widget([
                'name' => 'phone',
                'options' => ['class' => 'form-control customer-phone'],
                'clientOptions' => [
                    'source' => Url::to(['create-order/phone']),
                    'minLength'=>'1',
                    'limit' => '1'
                ],
            ]); ?>
            <span class="customer-label">Доп. телефон</span>
            <?= Html::textInput('second_phone', '',['class' => 'form-control']) ?>
        </div>

        <div class="form-group customer-form-btn">
            <?= Html::submitButton('Добавить клиента', ['class' => 'btn btn-save']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
    <div class="customer-search">
        <button class="btn btn-save customer-btn-search" ><span class="glyphicon glyphicon-search"></span></button>
    </div>
   <div class="customer-block">
       <div class="customer-order-title">История клиента</div>
       <div class="customer-order">
           <div class="wrapper" id="#loading">
               <div class="inner">
                   <span>З</span>
                   <span>а</span>
                   <span>г</span>
                   <span>р</span>
                   <span>у</span>
                   <span>з</span>
                   <span>к</span>
                   <span>а</span>
               </div>
           </div>
       </div>
   </div>

</div>

backend/views/create-order/customer_history.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 15.06.2018
 * Time: 15:55
 */

use yii\widgets\ListView;
use yii\helpers\Html;

/* @var $this \yii\web\view */
/* @var $customer \backend\models\Customer */
$this->registerJsFile(Yii::getAlias('@web') . '/js/get-modal.js', ['depends' => [yii\web\JqueryAsset::className()]]);
?>
<div class="customer-data-order">
    <div class="customer-history-control">
        <p><b>Ф.И.О.:  <?= $customer->full_name ?></b></p>
        <?= Html::a('Добавить заказ', ['/create-order/order', 'id' => $customer->id], ['class' => 'btn btn-add-order']); ?>
        <?= Html::a('<span class="glyphicon glyphicon-info-sign"></span> Перейти к клиенту', ['/customer/view', 'id' => $customer->id], ['class' => 'btn btn-add-order']) ?>
    </div>
    <div class="order-history">
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'summary' => '',
            'options' => ['data-pjax'=> true],
            'itemOptions' => ['class' => 'item'],
            'itemView' => function ($model) {
                return $this->renderAjax('_data_history',[
                    'model' => $model
                ]);
            },
        ]) ?>
    </div>
</div>